name: Fpdb3

on:
  push:
    branches:
      - '**'  # Match any branch
  pull_request:
    branches:
      - '**'  # Match any branch
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Update PATH
        run: |
          echo "C:\hostedtoolcache\windows\Python\3.11.x\x64\Scripts;C:\hostedtoolcache\windows\Python\3.11.x\x64" >> $env:GITHUB_PATH
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python.exe -m pip install -r requirements.txt
      - name: Build project
        shell: bash
        run: |
          ./build_fpdb.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/*
